spring.application.name=Hotels_DWBI

# ===============================
# DATABASE CONNECTION
# ===============================

# OLTP - oltp_user
spring.datasource.oltp-user.jdbc-url=jdbc:oracle:thin:@//localhost:1521/orclpdb.local
spring.datasource.oltp-user.username=sg
spring.datasource.oltp-user.password=parola
spring.datasource.oltp-user.driver-class-name=oracle.jdbc.OracleDriver

# OLTP - s3
spring.datasource.oltp-s3.jdbc-url=jdbc:oracle:thin:@//localhost:1521/orclpdb.local
spring.datasource.oltp-s3.username=s3
spring.datasource.oltp-s3.password=parola
spring.datasource.oltp-s3.driver-class-name=oracle.jdbc.OracleDriver


# OLTP-UE - s1
spring.datasource.oltp-ue-s1.jdbc-url=jdbc:oracle:thin:@//localhost:1521/mops_bd_ue
spring.datasource.oltp-ue-s1.username=s1
spring.datasource.oltp-ue-s1.password=parola
spring.datasource.oltp-ue-s1.driver-class-name=oracle.jdbc.OracleDriver

# OLTP-UE - s2
spring.datasource.oltp-ue-s2.jdbc-url=jdbc:oracle:thin:@//localhost:1521/mops_bd_ue
spring.datasource.oltp-ue-s2.username=s2
spring.datasource.oltp-ue-s2.password=parola
spring.datasource.oltp-ue-s2.driver-class-name=oracle.jdbc.OracleDriver

# Data warehouse (dims & facts — DW Propagation). Set user/password to match your DW schema.
#spring.datasource.dw.jdbc-url=jdbc:oracle:thin:@//localhost:1521/orclpdb.local
#spring.datasource.dw.username=dw_schema
#spring.datasource.dw.password=Pass123
#spring.datasource.dw.driver-class-name=oracle.jdbc.OracleDriver

# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect





# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# LOGGING (optional, but nice)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


