spring.application.name=Hotels_DWBI

# ===============================
# DATABASE CONNECTION
# ===============================

# OLTP
spring.datasource.oltp.jdbc-url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.oltp.username=hotel_oltp
spring.datasource.oltp.password=hotel123
spring.datasource.oltp.driver-class-name=oracle.jdbc.OracleDriver

# DW
spring.datasource.dw.jdbc-url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.dw.username=hotel_dw
spring.datasource.dw.password=hotel123
spring.datasource.dw.driver-class-name=oracle.jdbc.OracleDriver


# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect





# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# LOGGING (optional, but nice)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
